name: Build and Upload

on:
  push:
    branches: [ master, feat/**, release/** ]    
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [ 'Release' ]
        runtime-identifier: [ 'win-x64' ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
        cache: true
        cache-dependency-path: ISTA-Patcher/packages.lock.json

    - name: Restore dependencies
      run: dotnet restore --locked-mode
    
    - name: Publish the application
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: dotnet publish ISTA-Patcher --configuration ${{ matrix.configuration }} --runtime ${{ matrix.runtime-identifier }} --self-contained false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ISTA-Patcher-${{ matrix.runtime-identifier }}-${{ matrix.configuration }}
        path: |
          ISTA-Patcher/bin/${{ matrix.configuration }}/net8.0/${{ matrix.runtime-identifier }}/publish/*
          !ISTA-Patcher/bin/${{ matrix.configuration }}/net8.0/${{ matrix.runtime-identifier }}/publish/*.pdb
          !ISTA-Patcher/bin/${{ matrix.configuration }}/net8.0/${{ matrix.runtime-identifier }}/publish/*.dbg
